# @file
# SConstruct build script for this module.
#
import askapdev.rbuild.utils as utils
# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("imager")

pkg.AddSubPackage("distributedimager")
pkg.AddSubPackage("messages")

# Disable "shared" as MPE2 is not built with fPIC
pkg.build_shared = True;
pkg.build_static = False 

env.AppendUnique(CCFLAGS=['-O3'])
env.AppendUnique(CCFLAGS=['-fPIC'])

platform=utils.get_platform()
if platform['system'] == 'Darwin':
  env.AppendUnique(LINKFLAGS=['-framework', 'Python'])

# run the build process
pkg()
