#!/usr/bin/env bash
# Note that although this file is in a test-specific subdirectory, 
# the working directory when it executes is the root functests directory.
# Thus all paths should be relative to that location.

# Setup the environment
export TEST_DIR=`pwd`/test_large_spatial_search

# If data/large.db doesn't exist, create it now
if [ ! -f ./data/large.db ]; then
    COUNT=1000000
    echo Generating database with $COUNT random components
    source ../init_package_env.sh
    export AIPSPATH=$ASKAP_ROOT/Code/Base/accessors/current
    sms_tools --create-schema --config $TEST_DIR/sms.cfg --log-config ./config-files/logging.log_cfg &
    sms_tools --gen-random-components $COUNT --config $TEST_DIR/sms.cfg --log-config ./config-files/logging.log_cfg &
fi

# Note that this is not a recursive call, as the working directory is one 
# level up, so this file is not sourcing itself.
source ./sms
