# @file
# build script for AutoBuild

from askapdev.rbuild.builders import Scons as Builder
import askapdev.rbuild.utils as utils

platform =  utils.get_platform()
f = open("dependencies.default","w") 
f.write("#Automatically generated by build.py\n")
f.write("gsl=3rdParty/gsl/gsl-1.10\n")
f.write("askap=Code/Base/askap/current\n")
f.write("imagemath=Code/Base/imagemath/current\n")
f.write("blob=3rdParty/LOFAR/Blob/Blob-1.2;blob\n")
f.write("casacore=3rdParty/casacore/casacore-2.0.3; casa_images casa_coordinates casa_fits casa_lattices casa_measures casa_scimath casa_scimath_f casa_tables casa_casa\n")
f.write("fftw=3rdParty/fftw/fftw-3.3.3\n")

if platform['system'] == 'Darwin':
    f.write("#No LAPACK Compiled in OSX using Accelerate\n")
else:
    f.write("lapack=3rdParty/lapack/lapack-3.4.0\n")

f.close()



b = Builder(".")
b.build()

