# @file SConstruct
# SConstruct build script for this module.

# Always import this
from askapenv import env

env.AppendUnique(CCFLAGS=[
    '-O2',
    '-DASKAP_DEBUG',
    ])

# create build object with library name
pkg = env.AskapPackage("smsclient")

pkg.AddSubPackage("smsclient")

# run the build process
pkg()
