# @file SConstruct
# SConstruct build script for this module.
#

import os

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("correlatorsim")

pkg.AddSubPackage("simplayback")

env.AppendUnique(CCFLAGS=['-O2'])
env.AppendUnique(CCFLAGS=['-DASKAP_DEBUG'])

# Needed for Unit Tests
if 'AIPSPATH' not in os.environ:
    os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Base/accessors/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

# run the build process
pkg()
