# @file SConstruct
# SConstruct build script for this module.

# Always import this
from askapenv import env
import os

# create build object with library name
pkg = env.AskapPackage("calserviceaccessor")

pkg.AddSubPackage("calserviceaccessor")

env.AppendUnique(CCFLAGS=['-DASKAP_DEBUG'])


# run the build process
pkg()
