# @file SConstruct
# SConstruct build script for this module.

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("caldataaccessor")

pkg.AddSubPackage("calibrationaccessor")

env.AppendUnique(CCFLAGS=['-DASKAP_DEBUG'])

# run the build process
pkg()
