# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env
import sys

# create build object with library name
pkg = env.AskapPackage("simager")

pkg.AddSubPackage("messages")
pkg.AddSubPackage("distributedimager")

# Disable "shared" as MPE2 is not built with fPIC
pkg.build_shared = False;
pkg.build_static = True;

#env.AppendUnique(CCFLAGS=['-O3'])
#env.AppendUnique(CCFLAGS=['-Wno-unused-local-typedef'])

if sys.platform  == 'darwin':
  env.AppendUnique(LINKFLAGS=['-framework', 'Python'])


# run the build process
pkg()
