// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DATA_SOURCE_ODB_H
#define DATA_SOURCE_ODB_H

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "DataSource.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/query-dynamic.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // DataSource
  //
  template <>
  struct class_traits< ::askap::cp::sms::datamodel::DataSource >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::askap::cp::sms::datamodel::DataSource >
  {
    public:
    typedef ::askap::cp::sms::datamodel::DataSource object_type;
    typedef ::boost::shared_ptr< ::askap::cp::sms::datamodel::DataSource > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::askap::cp::sms::datamodel::id_type id_type;
    typedef ::askap::cp::sms::datamodel::version_type version_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  template <typename A>
  struct query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >
  {
    // version
    //
    typedef odb::query_column< ::askap::cp::sms::datamodel::version_type > version_type_;

    static version_type_ version;

    // data_source_id
    //
    typedef odb::query_column< ::askap::cp::sms::datamodel::id_type > data_source_id_type_;

    static data_source_id_type_ data_source_id;

    // name
    //
    typedef odb::query_column< ::std::string > name_type_;

    static name_type_ name;

    // catalogue_id
    //
    typedef odb::query_column< ::std::string > catalogue_id_type_;

    static catalogue_id_type_ catalogue_id;
  };

#ifdef ODB_COMMON_QUERY_COLUMNS_DEF

  template <typename A>
  typename query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::version_type_
  query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::version;

  template <typename A>
  typename query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::data_source_id_type_
  query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::data_source_id;

  template <typename A>
  typename query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::name_type_
  query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::name;

  template <typename A>
  typename query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::catalogue_id_type_
  query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >::catalogue_id;

#endif // ODB_COMMON_QUERY_COLUMNS_DEF

  template <typename A>
  struct pointer_query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >:
    query_columns< ::askap::cp::sms::datamodel::DataSource, id_common, A >
  {
  };

  template <>
  class access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_common >:
    public access::object_traits< ::askap::cp::sms::datamodel::DataSource >
  {
    public:
    typedef odb::query_base query_base_type;

    struct function_table_type
    {
      void (*persist) (database&, object_type&);
      pointer_type (*find1) (database&, const id_type&);
      bool (*find2) (database&, const id_type&, object_type&);
      bool (*reload) (database&, object_type&);
      void (*update) (database&, const object_type&);
      void (*erase1) (database&, const id_type&);
      void (*erase2) (database&, const object_type&);
      result<object_type> (*query) (database&, const query_base_type&);
      unsigned long long (*erase_query) (database&, const query_base_type&);
    };

    static const function_table_type* function_table[database_count];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);
  };

  // DataSource
  //
}

#include "DataSource-odb.i"

#include <odb/post.hxx>

#endif // DATA_SOURCE_ODB_H
