/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 1, 0);

