// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_MYSQL_QUERY_COLUMNS_DEF
#include "DataSource-odb-mysql.h"
#undef ODB_MYSQL_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>
#include <odb/function-table.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // DataSource
  //

  template struct query_columns<
    ::askap::cp::sms::datamodel::DataSource,
    id_mysql,
    access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql > >;

  struct access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::id_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          mysql::id_longlong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::id_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          mysql::id_longlong >::set_value (
        id,
        i.data_source_id_value,
        i.data_source_id_null);
    }

    return id;
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::version_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  version (const image_type& i)
  {
    version_type v;
    {
      mysql::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          mysql::id_longlong >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    return v;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // version
    //
    t[0UL] = 0;

    // data_source_id
    //
    t[1UL] = 0;

    // name
    //
    if (t[2UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // catalogue_id
    //
    if (t[3UL])
    {
      i.catalogue_id_value.capacity (i.catalogue_id_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // version
    //
    if (sk == statement_select)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.version_value;
      b[n].is_null = &i.version_null;
      n++;
    }

    // data_source_id
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.data_source_id_value;
      b[n].is_null = &i.data_source_id_null;
      n++;
    }

    // name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.name_value.capacity ());
    b[n].length = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // catalogue_id
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.catalogue_id_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.catalogue_id_value.capacity ());
    b[n].length = &i.catalogue_id_size;
    b[n].is_null = &i.catalogue_id_null;
    n++;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i, bool bv)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    if (bv)
    {
      n += 1;

      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.version_value;
      b[n].is_null = &i.version_null;
    }
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // data_source_id
    //
    if (sk == statement_insert)
    {
      ::askap::cp::sms::datamodel::id_type const& v =
        o.data_source_id;

      bool is_null (false);
      mysql::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          mysql::id_longlong >::set_image (
        i.data_source_id_value, is_null, v);
      i.data_source_id_null = is_null;
    }

    // name
    //
    {
      ::std::string const& v =
        o.name;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.name_value,
        size,
        is_null,
        v);
      i.name_null = is_null;
      i.name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.name_value.capacity ());
    }

    // catalogue_id
    //
    {
      ::std::string const& v =
        o.catalogue_id;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.catalogue_id_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.catalogue_id_value,
        size,
        is_null,
        v);
      i.catalogue_id_null = is_null;
      i.catalogue_id_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.catalogue_id_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // version
    //
    {
      ::askap::cp::sms::datamodel::version_type& v =
        o.version;

      mysql::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          mysql::id_longlong >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    // data_source_id
    //
    {
      ::askap::cp::sms::datamodel::id_type& v =
        o.data_source_id;

      mysql::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          mysql::id_longlong >::set_value (
        v,
        i.data_source_id_value,
        i.data_source_id_null);
    }

    // name
    //
    {
      ::std::string& v =
        o.name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // catalogue_id
    //
    {
      ::std::string& v =
        o.catalogue_id;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.catalogue_id_value,
        i.catalogue_id_size,
        i.catalogue_id_null);
    }
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  init (id_image_type& i, const id_type& id, const version_type* v)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          mysql::id_longlong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }

    if (v != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          mysql::id_longlong >::set_image (
        i.version_value, is_null, (*v));
      i.version_null = is_null;
    }
  }

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::persist_statement[] =
  "INSERT INTO `DataSource` "
  "(`version`, "
  "`data_source_id`, "
  "`name`, "
  "`catalogue_id`) "
  "VALUES "
  "(1, ?, ?, ?)";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::find_statement[] =
  "SELECT "
  "`DataSource`.`version`, "
  "`DataSource`.`data_source_id`, "
  "`DataSource`.`name`, "
  "`DataSource`.`catalogue_id` "
  "FROM `DataSource` "
  "WHERE `DataSource`.`data_source_id`=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::update_statement[] =
  "UPDATE `DataSource` "
  "SET "
  "`version`=`version`+1, "
  "`name`=?, "
  "`catalogue_id`=? "
  "WHERE `data_source_id`=? AND `version`=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::erase_statement[] =
  "DELETE FROM `DataSource` "
  "WHERE `data_source_id`=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::optimistic_erase_statement[] =
  "DELETE FROM `DataSource` "
  "WHERE `data_source_id`=? AND `version`=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::query_statement[] =
  "SELECT "
  "`DataSource`.`version`, "
  "`DataSource`.`data_source_id`, "
  "`DataSource`.`name`, "
  "`DataSource`.`catalogue_id` "
  "FROM `DataSource`";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::erase_query_statement[] =
  "DELETE FROM `DataSource`";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::table_name[] =
  "`DataSource`";

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.data_source_id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
        sts.optimistic_id_image_binding ().version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.data_source_id = id (sts.id_image ());

    obj.version = 1;

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.data_source_id);
    const version_type& v (
      obj.version);
    id_image_type& idi (sts.id_image ());
    init (idi, id, &v);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
        sts.optimistic_id_image_binding ().version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_changed ();

    const_cast< object_type& > (obj).version++;

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  erase (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db, obj, callback_event::pre_erase);

    const id_type& id  (
      obj.data_source_id);

    const version_type& v (
      obj.version);
    id_image_type& i (sts.id_image ());
    init (i, id, &v);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    if (sts.optimistic_erase_statement ().execute () != 1)
      throw object_changed ();

    pointer_cache_traits::erase (db, id);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::pointer_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.data_source_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    if (version (sts.image ()) == obj.version)
      return true;

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::object_type >
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::object_type >
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_common >::
  function_table_type function_table_askap_cp_sms_datamodel_DataSource_ =
  {
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::persist,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::find,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::find,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::reload,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::update,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::erase,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::erase,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::query,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::DataSource, id_mysql >::erase_query
  };

  static const object_function_table_entry< ::askap::cp::sms::datamodel::DataSource, id_mysql >
  function_table_entry_askap_cp_sms_datamodel_DataSource_ (
    &function_table_askap_cp_sms_datamodel_DataSource_);
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `DataSource`");
          db.execute ("CREATE TABLE IF NOT EXISTS `schema_version` (\n"
                      "  `name` VARCHAR(255) NOT NULL PRIMARY KEY,\n"
                      "  `version` BIGINT UNSIGNED NOT NULL,\n"
                      "  `migration` TINYINT(1) NOT NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("DELETE FROM `schema_version`\n"
                      "  WHERE `name` = ''");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `DataSource` (\n"
                      "  `version` BIGINT NOT NULL,\n"
                      "  `data_source_id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,\n"
                      "  `name` TEXT NOT NULL,\n"
                      "  `catalogue_id` TEXT NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE INDEX `data_source_id_i`\n"
                      "  ON `DataSource` (`data_source_id`)");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS `schema_version` (\n"
                      "  `name` VARCHAR(255) NOT NULL PRIMARY KEY,\n"
                      "  `version` BIGINT UNSIGNED NOT NULL,\n"
                      "  `migration` TINYINT(1) NOT NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("INSERT IGNORE INTO `schema_version` (\n"
                      "  `name`, `version`, `migration`)\n"
                      "  VALUES ('', 1, 0)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_mysql,
    "",
    1ULL,
    0);
}

#include <odb/post.hxx>
