/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Polarisation`;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

CREATE TABLE `Polarisation` (
  `version` BIGINT NOT NULL,
  `polarisation_component_id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `component_id` TEXT NOT NULL,
  `flux_I_median` DOUBLE NOT NULL,
  `flux_Q_median` DOUBLE NOT NULL,
  `flux_U_median` DOUBLE NOT NULL,
  `flux_V_median` DOUBLE NOT NULL,
  `rms_I` DOUBLE NOT NULL,
  `rms_Q` DOUBLE NOT NULL,
  `rms_U` DOUBLE NOT NULL,
  `rms_V` DOUBLE NOT NULL,
  `co_1` DOUBLE NOT NULL,
  `co_2` DOUBLE NOT NULL,
  `co_3` DOUBLE NOT NULL,
  `co_4` DOUBLE NOT NULL,
  `co_5` DOUBLE NOT NULL,
  `lambda_ref_sq` DOUBLE NOT NULL,
  `rmsf_fwhm` DOUBLE NOT NULL,
  `pol_peak` DOUBLE NOT NULL,
  `pol_peak_debias` DOUBLE NOT NULL,
  `pol_peak_err` DOUBLE NOT NULL,
  `pol_peak_fit` DOUBLE NOT NULL,
  `pol_peak_fit_debias` DOUBLE NOT NULL,
  `pol_peak_fit_err` DOUBLE NOT NULL,
  `pol_peak_fit_snr` DOUBLE NOT NULL,
  `pol_peak_fit_snr_err` DOUBLE NOT NULL,
  `fd_peak` DOUBLE NOT NULL,
  `fd_peak_err` DOUBLE NOT NULL,
  `fd_peak_fit` DOUBLE NOT NULL,
  `fd_peak_fit_err` DOUBLE NOT NULL,
  `pol_ang_ref` DOUBLE NOT NULL,
  `pol_ang_ref_err` DOUBLE NOT NULL,
  `pol_ang_zero` DOUBLE NOT NULL,
  `pol_ang_zero_err` DOUBLE NOT NULL,
  `pol_frac` DOUBLE NOT NULL,
  `pol_frac_err` DOUBLE NOT NULL,
  `complex_1` DOUBLE NOT NULL,
  `complex_2` DOUBLE NOT NULL,
  `flag_p1` INT NOT NULL,
  `flag_p2` INT NOT NULL,
  `flag_p3` INT NOT NULL,
  `flag_p4` INT NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `polarisation_component_id_i`
  ON `Polarisation` (`polarisation_component_id`);

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 1, 0);

