// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_SQLITE_QUERY_COLUMNS_DEF
#include "Polarisation-odb-sqlite.h"
#undef ODB_SQLITE_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>
#include <odb/function-table.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Polarisation
  //

  template struct query_columns<
    ::askap::cp::sms::datamodel::Polarisation,
    id_sqlite,
    access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite > >;

  struct access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::id_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::id_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.polarisation_component_id_value,
        i.polarisation_component_id_null);
    }

    return id;
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::version_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  version (const image_type& i)
  {
    version_type v;
    {
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          sqlite::id_integer >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    return v;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // version
    //
    t[0UL] = false;

    // polarisation_component_id
    //
    t[1UL] = false;

    // component_id
    //
    if (t[2UL])
    {
      i.component_id_value.capacity (i.component_id_size);
      grew = true;
    }

    // flux_I_median
    //
    t[3UL] = false;

    // flux_Q_median
    //
    t[4UL] = false;

    // flux_U_median
    //
    t[5UL] = false;

    // flux_V_median
    //
    t[6UL] = false;

    // rms_I
    //
    t[7UL] = false;

    // rms_Q
    //
    t[8UL] = false;

    // rms_U
    //
    t[9UL] = false;

    // rms_V
    //
    t[10UL] = false;

    // co_1
    //
    t[11UL] = false;

    // co_2
    //
    t[12UL] = false;

    // co_3
    //
    t[13UL] = false;

    // co_4
    //
    t[14UL] = false;

    // co_5
    //
    t[15UL] = false;

    // lambda_ref_sq
    //
    t[16UL] = false;

    // rmsf_fwhm
    //
    t[17UL] = false;

    // pol_peak
    //
    t[18UL] = false;

    // pol_peak_debias
    //
    t[19UL] = false;

    // pol_peak_err
    //
    t[20UL] = false;

    // pol_peak_fit
    //
    t[21UL] = false;

    // pol_peak_fit_debias
    //
    t[22UL] = false;

    // pol_peak_fit_err
    //
    t[23UL] = false;

    // pol_peak_fit_snr
    //
    t[24UL] = false;

    // pol_peak_fit_snr_err
    //
    t[25UL] = false;

    // fd_peak
    //
    t[26UL] = false;

    // fd_peak_err
    //
    t[27UL] = false;

    // fd_peak_fit
    //
    t[28UL] = false;

    // fd_peak_fit_err
    //
    t[29UL] = false;

    // pol_ang_ref
    //
    t[30UL] = false;

    // pol_ang_ref_err
    //
    t[31UL] = false;

    // pol_ang_zero
    //
    t[32UL] = false;

    // pol_ang_zero_err
    //
    t[33UL] = false;

    // pol_frac
    //
    t[34UL] = false;

    // pol_frac_err
    //
    t[35UL] = false;

    // complex_1
    //
    t[36UL] = false;

    // complex_2
    //
    t[37UL] = false;

    // flag_p1
    //
    t[38UL] = false;

    // flag_p2
    //
    t[39UL] = false;

    // flag_p3
    //
    t[40UL] = false;

    // flag_p4
    //
    t[41UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // version
    //
    if (sk == statement_select)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.version_value;
      b[n].is_null = &i.version_null;
      n++;
    }

    // polarisation_component_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.polarisation_component_id_value;
      b[n].is_null = &i.polarisation_component_id_null;
      n++;
    }

    // component_id
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.component_id_value.data ();
    b[n].size = &i.component_id_size;
    b[n].capacity = i.component_id_value.capacity ();
    b[n].is_null = &i.component_id_null;
    n++;

    // flux_I_median
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.flux_I_median_value;
    b[n].is_null = &i.flux_I_median_null;
    n++;

    // flux_Q_median
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.flux_Q_median_value;
    b[n].is_null = &i.flux_Q_median_null;
    n++;

    // flux_U_median
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.flux_U_median_value;
    b[n].is_null = &i.flux_U_median_null;
    n++;

    // flux_V_median
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.flux_V_median_value;
    b[n].is_null = &i.flux_V_median_null;
    n++;

    // rms_I
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.rms_I_value;
    b[n].is_null = &i.rms_I_null;
    n++;

    // rms_Q
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.rms_Q_value;
    b[n].is_null = &i.rms_Q_null;
    n++;

    // rms_U
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.rms_U_value;
    b[n].is_null = &i.rms_U_null;
    n++;

    // rms_V
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.rms_V_value;
    b[n].is_null = &i.rms_V_null;
    n++;

    // co_1
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.co_1_value;
    b[n].is_null = &i.co_1_null;
    n++;

    // co_2
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.co_2_value;
    b[n].is_null = &i.co_2_null;
    n++;

    // co_3
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.co_3_value;
    b[n].is_null = &i.co_3_null;
    n++;

    // co_4
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.co_4_value;
    b[n].is_null = &i.co_4_null;
    n++;

    // co_5
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.co_5_value;
    b[n].is_null = &i.co_5_null;
    n++;

    // lambda_ref_sq
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.lambda_ref_sq_value;
    b[n].is_null = &i.lambda_ref_sq_null;
    n++;

    // rmsf_fwhm
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.rmsf_fwhm_value;
    b[n].is_null = &i.rmsf_fwhm_null;
    n++;

    // pol_peak
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_value;
    b[n].is_null = &i.pol_peak_null;
    n++;

    // pol_peak_debias
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_debias_value;
    b[n].is_null = &i.pol_peak_debias_null;
    n++;

    // pol_peak_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_err_value;
    b[n].is_null = &i.pol_peak_err_null;
    n++;

    // pol_peak_fit
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_fit_value;
    b[n].is_null = &i.pol_peak_fit_null;
    n++;

    // pol_peak_fit_debias
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_fit_debias_value;
    b[n].is_null = &i.pol_peak_fit_debias_null;
    n++;

    // pol_peak_fit_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_fit_err_value;
    b[n].is_null = &i.pol_peak_fit_err_null;
    n++;

    // pol_peak_fit_snr
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_fit_snr_value;
    b[n].is_null = &i.pol_peak_fit_snr_null;
    n++;

    // pol_peak_fit_snr_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_peak_fit_snr_err_value;
    b[n].is_null = &i.pol_peak_fit_snr_err_null;
    n++;

    // fd_peak
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.fd_peak_value;
    b[n].is_null = &i.fd_peak_null;
    n++;

    // fd_peak_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.fd_peak_err_value;
    b[n].is_null = &i.fd_peak_err_null;
    n++;

    // fd_peak_fit
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.fd_peak_fit_value;
    b[n].is_null = &i.fd_peak_fit_null;
    n++;

    // fd_peak_fit_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.fd_peak_fit_err_value;
    b[n].is_null = &i.fd_peak_fit_err_null;
    n++;

    // pol_ang_ref
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_ang_ref_value;
    b[n].is_null = &i.pol_ang_ref_null;
    n++;

    // pol_ang_ref_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_ang_ref_err_value;
    b[n].is_null = &i.pol_ang_ref_err_null;
    n++;

    // pol_ang_zero
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_ang_zero_value;
    b[n].is_null = &i.pol_ang_zero_null;
    n++;

    // pol_ang_zero_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_ang_zero_err_value;
    b[n].is_null = &i.pol_ang_zero_err_null;
    n++;

    // pol_frac
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_frac_value;
    b[n].is_null = &i.pol_frac_null;
    n++;

    // pol_frac_err
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.pol_frac_err_value;
    b[n].is_null = &i.pol_frac_err_null;
    n++;

    // complex_1
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.complex_1_value;
    b[n].is_null = &i.complex_1_null;
    n++;

    // complex_2
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.complex_2_value;
    b[n].is_null = &i.complex_2_null;
    n++;

    // flag_p1
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.flag_p1_value;
    b[n].is_null = &i.flag_p1_null;
    n++;

    // flag_p2
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.flag_p2_value;
    b[n].is_null = &i.flag_p2_null;
    n++;

    // flag_p3
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.flag_p3_value;
    b[n].is_null = &i.flag_p3_null;
    n++;

    // flag_p4
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.flag_p4_value;
    b[n].is_null = &i.flag_p4_null;
    n++;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i, bool bv)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    if (bv)
    {
      n += 1;

      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.version_value;
      b[n].is_null = &i.version_null;
    }
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // polarisation_component_id
    //
    if (sk == statement_insert)
    {
      ::askap::cp::sms::datamodel::id_type const& v =
        o.polarisation_component_id;

      bool is_null (false);
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          sqlite::id_integer >::set_image (
        i.polarisation_component_id_value,
        is_null,
        v);
      i.polarisation_component_id_null = is_null;
    }

    // component_id
    //
    {
      ::std::string const& v =
        o.component_id;

      bool is_null (false);
      std::size_t cap (i.component_id_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.component_id_value,
        i.component_id_size,
        is_null,
        v);
      i.component_id_null = is_null;
      grew = grew || (cap != i.component_id_value.capacity ());
    }

    // flux_I_median
    //
    {
      double const& v =
        o.flux_I_median;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.flux_I_median_value,
        is_null,
        v);
      i.flux_I_median_null = is_null;
    }

    // flux_Q_median
    //
    {
      double const& v =
        o.flux_Q_median;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.flux_Q_median_value,
        is_null,
        v);
      i.flux_Q_median_null = is_null;
    }

    // flux_U_median
    //
    {
      double const& v =
        o.flux_U_median;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.flux_U_median_value,
        is_null,
        v);
      i.flux_U_median_null = is_null;
    }

    // flux_V_median
    //
    {
      double const& v =
        o.flux_V_median;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.flux_V_median_value,
        is_null,
        v);
      i.flux_V_median_null = is_null;
    }

    // rms_I
    //
    {
      double const& v =
        o.rms_I;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.rms_I_value,
        is_null,
        v);
      i.rms_I_null = is_null;
    }

    // rms_Q
    //
    {
      double const& v =
        o.rms_Q;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.rms_Q_value,
        is_null,
        v);
      i.rms_Q_null = is_null;
    }

    // rms_U
    //
    {
      double const& v =
        o.rms_U;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.rms_U_value,
        is_null,
        v);
      i.rms_U_null = is_null;
    }

    // rms_V
    //
    {
      double const& v =
        o.rms_V;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.rms_V_value,
        is_null,
        v);
      i.rms_V_null = is_null;
    }

    // co_1
    //
    {
      double const& v =
        o.co_1;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.co_1_value,
        is_null,
        v);
      i.co_1_null = is_null;
    }

    // co_2
    //
    {
      double const& v =
        o.co_2;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.co_2_value,
        is_null,
        v);
      i.co_2_null = is_null;
    }

    // co_3
    //
    {
      double const& v =
        o.co_3;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.co_3_value,
        is_null,
        v);
      i.co_3_null = is_null;
    }

    // co_4
    //
    {
      double const& v =
        o.co_4;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.co_4_value,
        is_null,
        v);
      i.co_4_null = is_null;
    }

    // co_5
    //
    {
      double const& v =
        o.co_5;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.co_5_value,
        is_null,
        v);
      i.co_5_null = is_null;
    }

    // lambda_ref_sq
    //
    {
      double const& v =
        o.lambda_ref_sq;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.lambda_ref_sq_value,
        is_null,
        v);
      i.lambda_ref_sq_null = is_null;
    }

    // rmsf_fwhm
    //
    {
      double const& v =
        o.rmsf_fwhm;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.rmsf_fwhm_value,
        is_null,
        v);
      i.rmsf_fwhm_null = is_null;
    }

    // pol_peak
    //
    {
      double const& v =
        o.pol_peak;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_value,
        is_null,
        v);
      i.pol_peak_null = is_null;
    }

    // pol_peak_debias
    //
    {
      double const& v =
        o.pol_peak_debias;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_debias_value,
        is_null,
        v);
      i.pol_peak_debias_null = is_null;
    }

    // pol_peak_err
    //
    {
      double const& v =
        o.pol_peak_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_err_value,
        is_null,
        v);
      i.pol_peak_err_null = is_null;
    }

    // pol_peak_fit
    //
    {
      double const& v =
        o.pol_peak_fit;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_fit_value,
        is_null,
        v);
      i.pol_peak_fit_null = is_null;
    }

    // pol_peak_fit_debias
    //
    {
      double const& v =
        o.pol_peak_fit_debias;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_fit_debias_value,
        is_null,
        v);
      i.pol_peak_fit_debias_null = is_null;
    }

    // pol_peak_fit_err
    //
    {
      double const& v =
        o.pol_peak_fit_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_fit_err_value,
        is_null,
        v);
      i.pol_peak_fit_err_null = is_null;
    }

    // pol_peak_fit_snr
    //
    {
      double const& v =
        o.pol_peak_fit_snr;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_fit_snr_value,
        is_null,
        v);
      i.pol_peak_fit_snr_null = is_null;
    }

    // pol_peak_fit_snr_err
    //
    {
      double const& v =
        o.pol_peak_fit_snr_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_peak_fit_snr_err_value,
        is_null,
        v);
      i.pol_peak_fit_snr_err_null = is_null;
    }

    // fd_peak
    //
    {
      double const& v =
        o.fd_peak;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.fd_peak_value,
        is_null,
        v);
      i.fd_peak_null = is_null;
    }

    // fd_peak_err
    //
    {
      double const& v =
        o.fd_peak_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.fd_peak_err_value,
        is_null,
        v);
      i.fd_peak_err_null = is_null;
    }

    // fd_peak_fit
    //
    {
      double const& v =
        o.fd_peak_fit;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.fd_peak_fit_value,
        is_null,
        v);
      i.fd_peak_fit_null = is_null;
    }

    // fd_peak_fit_err
    //
    {
      double const& v =
        o.fd_peak_fit_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.fd_peak_fit_err_value,
        is_null,
        v);
      i.fd_peak_fit_err_null = is_null;
    }

    // pol_ang_ref
    //
    {
      double const& v =
        o.pol_ang_ref;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_ang_ref_value,
        is_null,
        v);
      i.pol_ang_ref_null = is_null;
    }

    // pol_ang_ref_err
    //
    {
      double const& v =
        o.pol_ang_ref_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_ang_ref_err_value,
        is_null,
        v);
      i.pol_ang_ref_err_null = is_null;
    }

    // pol_ang_zero
    //
    {
      double const& v =
        o.pol_ang_zero;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_ang_zero_value,
        is_null,
        v);
      i.pol_ang_zero_null = is_null;
    }

    // pol_ang_zero_err
    //
    {
      double const& v =
        o.pol_ang_zero_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_ang_zero_err_value,
        is_null,
        v);
      i.pol_ang_zero_err_null = is_null;
    }

    // pol_frac
    //
    {
      double const& v =
        o.pol_frac;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_frac_value,
        is_null,
        v);
      i.pol_frac_null = is_null;
    }

    // pol_frac_err
    //
    {
      double const& v =
        o.pol_frac_err;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.pol_frac_err_value,
        is_null,
        v);
      i.pol_frac_err_null = is_null;
    }

    // complex_1
    //
    {
      double const& v =
        o.complex_1;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.complex_1_value,
        is_null,
        v);
      i.complex_1_null = is_null;
    }

    // complex_2
    //
    {
      double const& v =
        o.complex_2;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.complex_2_value,
        is_null,
        v);
      i.complex_2_null = is_null;
    }

    // flag_p1
    //
    {
      bool const& v =
        o.flag_p1;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.flag_p1_value,
        is_null,
        v);
      i.flag_p1_null = is_null;
    }

    // flag_p2
    //
    {
      bool const& v =
        o.flag_p2;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.flag_p2_value,
        is_null,
        v);
      i.flag_p2_null = is_null;
    }

    // flag_p3
    //
    {
      bool const& v =
        o.flag_p3;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.flag_p3_value,
        is_null,
        v);
      i.flag_p3_null = is_null;
    }

    // flag_p4
    //
    {
      bool const& v =
        o.flag_p4;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.flag_p4_value,
        is_null,
        v);
      i.flag_p4_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // version
    //
    {
      ::askap::cp::sms::datamodel::version_type& v =
        o.version;

      sqlite::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          sqlite::id_integer >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    // polarisation_component_id
    //
    {
      ::askap::cp::sms::datamodel::id_type& v =
        o.polarisation_component_id;

      sqlite::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          sqlite::id_integer >::set_value (
        v,
        i.polarisation_component_id_value,
        i.polarisation_component_id_null);
    }

    // component_id
    //
    {
      ::std::string& v =
        o.component_id;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.component_id_value,
        i.component_id_size,
        i.component_id_null);
    }

    // flux_I_median
    //
    {
      double& v =
        o.flux_I_median;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.flux_I_median_value,
        i.flux_I_median_null);
    }

    // flux_Q_median
    //
    {
      double& v =
        o.flux_Q_median;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.flux_Q_median_value,
        i.flux_Q_median_null);
    }

    // flux_U_median
    //
    {
      double& v =
        o.flux_U_median;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.flux_U_median_value,
        i.flux_U_median_null);
    }

    // flux_V_median
    //
    {
      double& v =
        o.flux_V_median;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.flux_V_median_value,
        i.flux_V_median_null);
    }

    // rms_I
    //
    {
      double& v =
        o.rms_I;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.rms_I_value,
        i.rms_I_null);
    }

    // rms_Q
    //
    {
      double& v =
        o.rms_Q;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.rms_Q_value,
        i.rms_Q_null);
    }

    // rms_U
    //
    {
      double& v =
        o.rms_U;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.rms_U_value,
        i.rms_U_null);
    }

    // rms_V
    //
    {
      double& v =
        o.rms_V;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.rms_V_value,
        i.rms_V_null);
    }

    // co_1
    //
    {
      double& v =
        o.co_1;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.co_1_value,
        i.co_1_null);
    }

    // co_2
    //
    {
      double& v =
        o.co_2;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.co_2_value,
        i.co_2_null);
    }

    // co_3
    //
    {
      double& v =
        o.co_3;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.co_3_value,
        i.co_3_null);
    }

    // co_4
    //
    {
      double& v =
        o.co_4;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.co_4_value,
        i.co_4_null);
    }

    // co_5
    //
    {
      double& v =
        o.co_5;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.co_5_value,
        i.co_5_null);
    }

    // lambda_ref_sq
    //
    {
      double& v =
        o.lambda_ref_sq;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.lambda_ref_sq_value,
        i.lambda_ref_sq_null);
    }

    // rmsf_fwhm
    //
    {
      double& v =
        o.rmsf_fwhm;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.rmsf_fwhm_value,
        i.rmsf_fwhm_null);
    }

    // pol_peak
    //
    {
      double& v =
        o.pol_peak;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_value,
        i.pol_peak_null);
    }

    // pol_peak_debias
    //
    {
      double& v =
        o.pol_peak_debias;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_debias_value,
        i.pol_peak_debias_null);
    }

    // pol_peak_err
    //
    {
      double& v =
        o.pol_peak_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_err_value,
        i.pol_peak_err_null);
    }

    // pol_peak_fit
    //
    {
      double& v =
        o.pol_peak_fit;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_fit_value,
        i.pol_peak_fit_null);
    }

    // pol_peak_fit_debias
    //
    {
      double& v =
        o.pol_peak_fit_debias;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_fit_debias_value,
        i.pol_peak_fit_debias_null);
    }

    // pol_peak_fit_err
    //
    {
      double& v =
        o.pol_peak_fit_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_fit_err_value,
        i.pol_peak_fit_err_null);
    }

    // pol_peak_fit_snr
    //
    {
      double& v =
        o.pol_peak_fit_snr;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_fit_snr_value,
        i.pol_peak_fit_snr_null);
    }

    // pol_peak_fit_snr_err
    //
    {
      double& v =
        o.pol_peak_fit_snr_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_peak_fit_snr_err_value,
        i.pol_peak_fit_snr_err_null);
    }

    // fd_peak
    //
    {
      double& v =
        o.fd_peak;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.fd_peak_value,
        i.fd_peak_null);
    }

    // fd_peak_err
    //
    {
      double& v =
        o.fd_peak_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.fd_peak_err_value,
        i.fd_peak_err_null);
    }

    // fd_peak_fit
    //
    {
      double& v =
        o.fd_peak_fit;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.fd_peak_fit_value,
        i.fd_peak_fit_null);
    }

    // fd_peak_fit_err
    //
    {
      double& v =
        o.fd_peak_fit_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.fd_peak_fit_err_value,
        i.fd_peak_fit_err_null);
    }

    // pol_ang_ref
    //
    {
      double& v =
        o.pol_ang_ref;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_ang_ref_value,
        i.pol_ang_ref_null);
    }

    // pol_ang_ref_err
    //
    {
      double& v =
        o.pol_ang_ref_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_ang_ref_err_value,
        i.pol_ang_ref_err_null);
    }

    // pol_ang_zero
    //
    {
      double& v =
        o.pol_ang_zero;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_ang_zero_value,
        i.pol_ang_zero_null);
    }

    // pol_ang_zero_err
    //
    {
      double& v =
        o.pol_ang_zero_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_ang_zero_err_value,
        i.pol_ang_zero_err_null);
    }

    // pol_frac
    //
    {
      double& v =
        o.pol_frac;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_frac_value,
        i.pol_frac_null);
    }

    // pol_frac_err
    //
    {
      double& v =
        o.pol_frac_err;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.pol_frac_err_value,
        i.pol_frac_err_null);
    }

    // complex_1
    //
    {
      double& v =
        o.complex_1;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.complex_1_value,
        i.complex_1_null);
    }

    // complex_2
    //
    {
      double& v =
        o.complex_2;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.complex_2_value,
        i.complex_2_null);
    }

    // flag_p1
    //
    {
      bool& v =
        o.flag_p1;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.flag_p1_value,
        i.flag_p1_null);
    }

    // flag_p2
    //
    {
      bool& v =
        o.flag_p2;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.flag_p2_value,
        i.flag_p2_null);
    }

    // flag_p3
    //
    {
      bool& v =
        o.flag_p3;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.flag_p3_value,
        i.flag_p3_null);
    }

    // flag_p4
    //
    {
      bool& v =
        o.flag_p4;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.flag_p4_value,
        i.flag_p4_null);
    }
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  init (id_image_type& i, const id_type& id, const version_type* v)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::id_type,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }

    if (v != 0)
    {
      bool is_null (false);
      sqlite::value_traits<
          ::askap::cp::sms::datamodel::version_type,
          sqlite::id_integer >::set_image (
        i.version_value,
        is_null,
        (*v));
      i.version_null = is_null;
    }
  }

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Polarisation\" "
  "(\"version\", "
  "\"polarisation_component_id\", "
  "\"component_id\", "
  "\"flux_I_median\", "
  "\"flux_Q_median\", "
  "\"flux_U_median\", "
  "\"flux_V_median\", "
  "\"rms_I\", "
  "\"rms_Q\", "
  "\"rms_U\", "
  "\"rms_V\", "
  "\"co_1\", "
  "\"co_2\", "
  "\"co_3\", "
  "\"co_4\", "
  "\"co_5\", "
  "\"lambda_ref_sq\", "
  "\"rmsf_fwhm\", "
  "\"pol_peak\", "
  "\"pol_peak_debias\", "
  "\"pol_peak_err\", "
  "\"pol_peak_fit\", "
  "\"pol_peak_fit_debias\", "
  "\"pol_peak_fit_err\", "
  "\"pol_peak_fit_snr\", "
  "\"pol_peak_fit_snr_err\", "
  "\"fd_peak\", "
  "\"fd_peak_err\", "
  "\"fd_peak_fit\", "
  "\"fd_peak_fit_err\", "
  "\"pol_ang_ref\", "
  "\"pol_ang_ref_err\", "
  "\"pol_ang_zero\", "
  "\"pol_ang_zero_err\", "
  "\"pol_frac\", "
  "\"pol_frac_err\", "
  "\"complex_1\", "
  "\"complex_2\", "
  "\"flag_p1\", "
  "\"flag_p2\", "
  "\"flag_p3\", "
  "\"flag_p4\") "
  "VALUES "
  "(1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Polarisation\".\"version\", "
  "\"Polarisation\".\"polarisation_component_id\", "
  "\"Polarisation\".\"component_id\", "
  "\"Polarisation\".\"flux_I_median\", "
  "\"Polarisation\".\"flux_Q_median\", "
  "\"Polarisation\".\"flux_U_median\", "
  "\"Polarisation\".\"flux_V_median\", "
  "\"Polarisation\".\"rms_I\", "
  "\"Polarisation\".\"rms_Q\", "
  "\"Polarisation\".\"rms_U\", "
  "\"Polarisation\".\"rms_V\", "
  "\"Polarisation\".\"co_1\", "
  "\"Polarisation\".\"co_2\", "
  "\"Polarisation\".\"co_3\", "
  "\"Polarisation\".\"co_4\", "
  "\"Polarisation\".\"co_5\", "
  "\"Polarisation\".\"lambda_ref_sq\", "
  "\"Polarisation\".\"rmsf_fwhm\", "
  "\"Polarisation\".\"pol_peak\", "
  "\"Polarisation\".\"pol_peak_debias\", "
  "\"Polarisation\".\"pol_peak_err\", "
  "\"Polarisation\".\"pol_peak_fit\", "
  "\"Polarisation\".\"pol_peak_fit_debias\", "
  "\"Polarisation\".\"pol_peak_fit_err\", "
  "\"Polarisation\".\"pol_peak_fit_snr\", "
  "\"Polarisation\".\"pol_peak_fit_snr_err\", "
  "\"Polarisation\".\"fd_peak\", "
  "\"Polarisation\".\"fd_peak_err\", "
  "\"Polarisation\".\"fd_peak_fit\", "
  "\"Polarisation\".\"fd_peak_fit_err\", "
  "\"Polarisation\".\"pol_ang_ref\", "
  "\"Polarisation\".\"pol_ang_ref_err\", "
  "\"Polarisation\".\"pol_ang_zero\", "
  "\"Polarisation\".\"pol_ang_zero_err\", "
  "\"Polarisation\".\"pol_frac\", "
  "\"Polarisation\".\"pol_frac_err\", "
  "\"Polarisation\".\"complex_1\", "
  "\"Polarisation\".\"complex_2\", "
  "\"Polarisation\".\"flag_p1\", "
  "\"Polarisation\".\"flag_p2\", "
  "\"Polarisation\".\"flag_p3\", "
  "\"Polarisation\".\"flag_p4\" "
  "FROM \"Polarisation\" "
  "WHERE \"Polarisation\".\"polarisation_component_id\"=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::update_statement[] =
  "UPDATE \"Polarisation\" "
  "SET "
  "\"version\"=\"version\"+1, "
  "\"component_id\"=?, "
  "\"flux_I_median\"=?, "
  "\"flux_Q_median\"=?, "
  "\"flux_U_median\"=?, "
  "\"flux_V_median\"=?, "
  "\"rms_I\"=?, "
  "\"rms_Q\"=?, "
  "\"rms_U\"=?, "
  "\"rms_V\"=?, "
  "\"co_1\"=?, "
  "\"co_2\"=?, "
  "\"co_3\"=?, "
  "\"co_4\"=?, "
  "\"co_5\"=?, "
  "\"lambda_ref_sq\"=?, "
  "\"rmsf_fwhm\"=?, "
  "\"pol_peak\"=?, "
  "\"pol_peak_debias\"=?, "
  "\"pol_peak_err\"=?, "
  "\"pol_peak_fit\"=?, "
  "\"pol_peak_fit_debias\"=?, "
  "\"pol_peak_fit_err\"=?, "
  "\"pol_peak_fit_snr\"=?, "
  "\"pol_peak_fit_snr_err\"=?, "
  "\"fd_peak\"=?, "
  "\"fd_peak_err\"=?, "
  "\"fd_peak_fit\"=?, "
  "\"fd_peak_fit_err\"=?, "
  "\"pol_ang_ref\"=?, "
  "\"pol_ang_ref_err\"=?, "
  "\"pol_ang_zero\"=?, "
  "\"pol_ang_zero_err\"=?, "
  "\"pol_frac\"=?, "
  "\"pol_frac_err\"=?, "
  "\"complex_1\"=?, "
  "\"complex_2\"=?, "
  "\"flag_p1\"=?, "
  "\"flag_p2\"=?, "
  "\"flag_p3\"=?, "
  "\"flag_p4\"=? "
  "WHERE \"polarisation_component_id\"=? AND \"version\"=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Polarisation\" "
  "WHERE \"polarisation_component_id\"=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::optimistic_erase_statement[] =
  "DELETE FROM \"Polarisation\" "
  "WHERE \"polarisation_component_id\"=? AND \"version\"=?";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::query_statement[] =
  "SELECT "
  "\"Polarisation\".\"version\", "
  "\"Polarisation\".\"polarisation_component_id\", "
  "\"Polarisation\".\"component_id\", "
  "\"Polarisation\".\"flux_I_median\", "
  "\"Polarisation\".\"flux_Q_median\", "
  "\"Polarisation\".\"flux_U_median\", "
  "\"Polarisation\".\"flux_V_median\", "
  "\"Polarisation\".\"rms_I\", "
  "\"Polarisation\".\"rms_Q\", "
  "\"Polarisation\".\"rms_U\", "
  "\"Polarisation\".\"rms_V\", "
  "\"Polarisation\".\"co_1\", "
  "\"Polarisation\".\"co_2\", "
  "\"Polarisation\".\"co_3\", "
  "\"Polarisation\".\"co_4\", "
  "\"Polarisation\".\"co_5\", "
  "\"Polarisation\".\"lambda_ref_sq\", "
  "\"Polarisation\".\"rmsf_fwhm\", "
  "\"Polarisation\".\"pol_peak\", "
  "\"Polarisation\".\"pol_peak_debias\", "
  "\"Polarisation\".\"pol_peak_err\", "
  "\"Polarisation\".\"pol_peak_fit\", "
  "\"Polarisation\".\"pol_peak_fit_debias\", "
  "\"Polarisation\".\"pol_peak_fit_err\", "
  "\"Polarisation\".\"pol_peak_fit_snr\", "
  "\"Polarisation\".\"pol_peak_fit_snr_err\", "
  "\"Polarisation\".\"fd_peak\", "
  "\"Polarisation\".\"fd_peak_err\", "
  "\"Polarisation\".\"fd_peak_fit\", "
  "\"Polarisation\".\"fd_peak_fit_err\", "
  "\"Polarisation\".\"pol_ang_ref\", "
  "\"Polarisation\".\"pol_ang_ref_err\", "
  "\"Polarisation\".\"pol_ang_zero\", "
  "\"Polarisation\".\"pol_ang_zero_err\", "
  "\"Polarisation\".\"pol_frac\", "
  "\"Polarisation\".\"pol_frac_err\", "
  "\"Polarisation\".\"complex_1\", "
  "\"Polarisation\".\"complex_2\", "
  "\"Polarisation\".\"flag_p1\", "
  "\"Polarisation\".\"flag_p2\", "
  "\"Polarisation\".\"flag_p3\", "
  "\"Polarisation\".\"flag_p4\" "
  "FROM \"Polarisation\"";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Polarisation\"";

  const char access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::table_name[] =
  "\"Polarisation\"";

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.polarisation_component_id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
        sts.optimistic_id_image_binding ().version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.polarisation_component_id = id (sts.id_image ());

    obj.version = 1;

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.polarisation_component_id);
    const version_type& v (
      obj.version);
    id_image_type& idi (sts.id_image ());
    init (idi, id, &v);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
        sts.optimistic_id_image_binding ().version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_changed ();

    const_cast< object_type& > (obj).version++;

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  void access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  erase (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db, obj, callback_event::pre_erase);

    const id_type& id  (
      obj.polarisation_component_id);

    const version_type& v (
      obj.version);
    id_image_type& i (sts.id_image ());
    init (i, id, &v);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    if (sts.optimistic_erase_statement ().execute () != 1)
      throw object_changed ();

    pointer_cache_traits::erase (db, id);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::pointer_type
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.polarisation_component_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    if (version (sts.image ()) == obj.version)
      return true;

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
      sts.optimistic_id_image_binding ().version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::object_type >
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::object_type >
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_common >::
  function_table_type function_table_askap_cp_sms_datamodel_Polarisation_ =
  {
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::persist,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::find,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::find,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::reload,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::update,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::erase,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::erase,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::query,
    &access::object_traits_impl< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >::erase_query
  };

  static const object_function_table_entry< ::askap::cp::sms::datamodel::Polarisation, id_sqlite >
  function_table_entry_askap_cp_sms_datamodel_Polarisation_ (
    &function_table_askap_cp_sms_datamodel_Polarisation_);
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"Polarisation\"");
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("DELETE FROM \"schema_version\"\n"
                      "  WHERE \"name\" = ''");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"Polarisation\" (\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"polarisation_component_id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"component_id\" TEXT NOT NULL,\n"
                      "  \"flux_I_median\" REAL NOT NULL,\n"
                      "  \"flux_Q_median\" REAL NOT NULL,\n"
                      "  \"flux_U_median\" REAL NOT NULL,\n"
                      "  \"flux_V_median\" REAL NOT NULL,\n"
                      "  \"rms_I\" REAL NOT NULL,\n"
                      "  \"rms_Q\" REAL NOT NULL,\n"
                      "  \"rms_U\" REAL NOT NULL,\n"
                      "  \"rms_V\" REAL NOT NULL,\n"
                      "  \"co_1\" REAL NOT NULL,\n"
                      "  \"co_2\" REAL NOT NULL,\n"
                      "  \"co_3\" REAL NOT NULL,\n"
                      "  \"co_4\" REAL NOT NULL,\n"
                      "  \"co_5\" REAL NOT NULL,\n"
                      "  \"lambda_ref_sq\" REAL NOT NULL,\n"
                      "  \"rmsf_fwhm\" REAL NOT NULL,\n"
                      "  \"pol_peak\" REAL NOT NULL,\n"
                      "  \"pol_peak_debias\" REAL NOT NULL,\n"
                      "  \"pol_peak_err\" REAL NOT NULL,\n"
                      "  \"pol_peak_fit\" REAL NOT NULL,\n"
                      "  \"pol_peak_fit_debias\" REAL NOT NULL,\n"
                      "  \"pol_peak_fit_err\" REAL NOT NULL,\n"
                      "  \"pol_peak_fit_snr\" REAL NOT NULL,\n"
                      "  \"pol_peak_fit_snr_err\" REAL NOT NULL,\n"
                      "  \"fd_peak\" REAL NOT NULL,\n"
                      "  \"fd_peak_err\" REAL NOT NULL,\n"
                      "  \"fd_peak_fit\" REAL NOT NULL,\n"
                      "  \"fd_peak_fit_err\" REAL NOT NULL,\n"
                      "  \"pol_ang_ref\" REAL NOT NULL,\n"
                      "  \"pol_ang_ref_err\" REAL NOT NULL,\n"
                      "  \"pol_ang_zero\" REAL NOT NULL,\n"
                      "  \"pol_ang_zero_err\" REAL NOT NULL,\n"
                      "  \"pol_frac\" REAL NOT NULL,\n"
                      "  \"pol_frac_err\" REAL NOT NULL,\n"
                      "  \"complex_1\" REAL NOT NULL,\n"
                      "  \"complex_2\" REAL NOT NULL,\n"
                      "  \"flag_p1\" INT NOT NULL,\n"
                      "  \"flag_p2\" INT NOT NULL,\n"
                      "  \"flag_p3\" INT NOT NULL,\n"
                      "  \"flag_p4\" INT NOT NULL)");
          db.execute ("CREATE INDEX \"Polarisation_polarisation_component_id_i\"\n"
                      "  ON \"Polarisation\" (\"polarisation_component_id\")");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("INSERT OR IGNORE INTO \"schema_version\" (\n"
                      "  \"name\", \"version\", \"migration\")\n"
                      "  VALUES ('', 1, 0)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_sqlite,
    "",
    1ULL,
    0);
}

#include <odb/post.hxx>
