# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env
import sys
# create build object with library name
pkg = env.AskapPackage("pipelinetasks")

pkg.AddSubPackage("cmodel")
pkg.AddSubPackage("cflag")
pkg.AddSubPackage("makecube")
pkg.AddSubPackage("mssplit")
pkg.AddSubPackage("casdaupload")

env.Append(CCFLAGS=['-O2'])

if sys.platform  == 'darwin':
  env.AppendUnique(LINKFLAGS=['-framework', 'Python'])



# run the build process
pkg()
