pipeline {
  agent {
    docker {
      image 'sord/yanda:latest'
    }

  }
  stages {
    stage('Building base-askap') {
      steps {
        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop') {
          sh '''if [ -d base-askap ]; then
echo "base-askap directory already exists"
rm -rf base-askap
fi
git clone https://bitbucket.csiro.au/scm/askapsdp/base-askap.git
cd base-askap
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ../
make -j2
make -j2 install
'''
        }

      }
    }
    stage('Building base-logfilters') {
      steps {
        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop') {
          sh '''if [ -d base-logfilters ]; then
echo "base-logfilters directory already exists"
rm -rf base-logfilters
fi
git clone https://bitbucket.csiro.au/scm/askapsdp/base-logfilters.git
cd base-logfilters
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ../
make -j2
make -j2 install
'''
        }

      }
    }
    stage('Building base-imagemath') {
      steps {
        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop') {
          sh '''if [ -d build ]; then
echo "base-imagemath build directory already exists"
cd build
if [ -f install_manifest.txt ]; then
make uninstall
cd ..
fi
rm -rf build
mkdir build
else
mkdir build
fi'''
        }

        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop/build') {
          sh '''cmake -DASKAP_ROOT_DIR=${WORKSPACE}/base-askap_develop/install -DCMAKE_INSTALL_PREFIX=${PREFIX} ../
make -j2
make -j2 install
'''
        }

      }
    }
  }
  environment {
    WORKSPACE = '/var/lib/jenkins/workspace'
    PREFIX = '/var/lib/jenkins/workspace/base-imagemath_develop/install'
  }
}
