pipeline {
  agent {
    docker {
      image 'sord/yanda:latest'
    }

  }
  stages {
    stage('Building') {
      steps {
        sh '''if [ -d ${WORKSPACE}/base-askap_develop/ ]; then
echo "base-askap directory exists"
else
echo "cannot access base-access"
fi
'''
        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop') {
          sh '''if [ -d build ]; then
echo "base-askap build directory already exists"
cd build
if [ -f install_manifest.txt ]; then
make uninstall
cd ..
fi
rm -rf build
mkdir build
else
mkdir build
fi'''
        }

        dir(path: '/var/lib/jenkins/workspace/base-imagemath_develop/build') {
          sh '''cmake -DASKAP_ROOT_DIR=${WORKSPACE}/base-askap_develop/install -DCMAKE_INSTALL_PREFIX=${PREFIX} ../
make -j2
make -j2 install
'''
        }

      }
    }
  }
  environment {
    WORKSPACE = '/var/lib/jenkins/workspace'
    PREFIX = '/var/lib/jenkins/workspace/base-imagemath_develop/install'
  }
}