# @file
# SConstruct build script for this module.
# Package dependencies are read from 'dependencies.default'
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env

env.AppendUnique(CCFLAGS=['-O3'])

# create build object with library name
pkg = env.AskapPackage("imagemath")

# add sub packages 
pkg.AddSubPackage("linmos")

# run the build process
pkg()
