#!/usr/bin/env bash
# Note that although this file is in a test-specific subdirectory, 
# the working directory when it executes is the root functests directory.
# Thus all paths should be relative to that location.

# Setup the environment
export TEST_DIR=`pwd`/test_sbstate_changed

# Note that this is not a recursive call, as the working directory means this 
# file is not sourcing itself.
source ./manager
