pipeline {
  agent {
    docker {
      image 'sord/yanda:latest'
    }

  }
  stages {
    stage('Building') {
    steps { 
        sh '''if [ -d /var/lib/jenkins/workspace/base/install ]; then
echo "base directory already exists - checking for install"
if [ -d /var/lib/jenkins/workspace/base/install ]; then
echo "install exists - removing"
rm -rf /var/lib/jenkins/workspace/base/install
else
mkdir /var/lib/jenkins/workspace/base
fi''' 
        dir(path: '/var/lib/jenkins/workspace/base-askap_develop') {
          sh '''if [ -d build ]; then
echo "base-askap build directory already exists"
rm -rf build
mkdir build
else
mkdir build
fi'''
        }

        dir(path: '/var/lib/jenkins/workspace/base-askap_develop/build') {
	  sh '''cmake ../ -DCMAKE_INSTALL_PREFIX=${PREFIX}
make -j2
make -j2 install
'''

       }
      }
    }
  }
  
  environment {
    WORKSPACE = '/var/lib/jenkins/workspace'
    PREFIX = '/var/lib/jenkins/workspace/base/install'
  }
}
