pipeline {
  agent {
    docker {
      image 'sord/yanda:latest'
    }

  }
  stages {
    stage('Building') {
      steps {
        dir(path: '.') {
          sh '''if [ -d build ]; then
echo "base-askap build directory already exists"
cd build
if [ -f install_manifest.txt ]; then
cd make uninstall
fi
cd ..
rm -rf build
mkdir build
else
mkdir build
fi'''
        }

        dir(path: 'build') {
          sh '''cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ../
make -j2
make -j2 install
'''
        }

      }
    }
  }
  environment {
    WORKSPACE = pwd()
    PREFIX = "${WORKSPACE}/install"
  }
}
