# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("components")

pkg.AddSubPackage("components")

env.Append(CCFLAGS=['-O3'])
# for casarest
env.AppendUnique(CCFLAGS=['-I/usr/local/include/casarest'])
# run the build process
pkg()
