# @file SConstruct
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("cpcommon")

pkg.AddSubPackage("cpcommon")

env.AppendUnique(CCFLAGS=['-I/usr/local/include/casarest'])
env.AppendUnique(CCFLAGS=['-I/usr/local/include/casacore'])
env.AppendUnique(CCFLAGS=['-Dcasa=casacore'])
env.AppendUnique(CCFLAGS=['-DHAVE_AIPSPP'])
# run the build process
pkg()
